#need to save as ASCII ***
setwd('F:/HPM_UAT/DGIS_InputOutput/csv')
#setwd('D:/20181220/csv')

#install.packages("RJSONIO")
library(RJSONIO)

json_data<- list() # creates a list
final<- list()
no <- list()
h1 <- list()
h2 <- list()
h3 <- list()
h4 <- list()
h5 <- list()
h6 <- list()
h7 <- list()
h8 <- list()
h9 <- list()
h10<- list()
h11<- list()
h12<- list()
h13<- list()
h14<- list()
h15<- list()
h16<- list()
h17<- list()
h18<- list()
h19<- list()
h20<- list()
h21<- list()
h22<- list()
h23<- list()
h24<- list()
h25<- list()
h26<- list()
h27<- list()
h28<- list()
h29<- list()
h30<- list()
h31<- list()
h32<- list()
h33<- list()
h34<- list()
h35<- list()
h36<- list()
h37<- list()
h38<- list()
h39<- list()
h40<- list()
h41<- list()
h42<- list()
h43<- list()
h44<- list()
h45<- list()
h46<- list()
h47<- list()
h48<- list()
h49<- list()
h50<- list()
h51<- list()
h52<- list()
h53<- list()
h54<- list()
h55<- list()
h56<- list()
h57<- list()
h58<- list()
h59<- list()
h60<- list()
h61<- list()
h62<- list()
h63<- list()
h64<- list()
h65<- list()
h66<- list()
h67<- list()
h68<- list()
h69<- list()
h70<- list()
h71<- list()
h72<- list()
h73<- list()
h74<- list()
h75<- list()
h76<- list()
h77<- list()
h78<- list()
h79<- list()
h80<- list()
h81<- list()
h82<- list()
h83<- list()
h84<- list()
h85<- list()
h86<- list()
h87<- list()
h88<- list()
h89<- list()
h90<- list()
h91<- list()
h92<- list()
h93<- list()
h94<- list()

listjson <- dir(pattern = "*.json") # creates the list of all the json files in the directory
for (k in 1:length(listjson)){
no[[k]]<- list('no'	=gsub(".json","",listjson[k]))
 json_data[[k]] <- fromJSON(listjson[k])
h1[[k]]<-list('ApplicationNbr'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ApplicationNbr)
h2[[k]]<-list('CollateralNbr'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CollateralNbr)
h3[[k]]<-list('ZipCode'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ZipCode)
h4[[k]]<-list('SectorNum'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$SectorNum)
h5[[k]]<-list('LocationCode'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LocationCode)
h6[[k]]<-list('PublicRatio'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$PublicRatio)
h7[[k]]<-list('RStallAppraisePrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$RStallAppraisePrice)
h8[[k]]<-list('StallArea'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$StallArea)
h9[[k]]<-list('BuildingNameFlg'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$BuildingNameFlg)
h10[[k]]<-list('TargetNewFlg'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$TargetNewFlg)
h11[[k]]<-list('CountOfNegativeCode'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CountOfNegativeCode)
h12[[k]]<-list('AvgPriceL6m'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AvgPriceL6m)
h13[[k]]<-list('Exclusion'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$Exclusion)
h14[[k]]<-list('TotalBuildingArea'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$TotalBuildingArea)
h15[[k]]<-list('StallCountsP'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$StallCountsP)
h16[[k]]<-list('StallCountsM'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$StallCountsM)
h17[[k]]<-list('ActuralHousePriceCounts'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralHousePriceCounts)
h18[[k]]<-list('ActuralHousePriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralHousePriceMean)
h19[[k]]<-list('ActuralHousePriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralHousePriceP50)
h20[[k]]<-list('ActuralHousePriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralHousePriceP5)
h21[[k]]<-list('ActuralHousePriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralHousePriceP95)
h22[[k]]<-list('AgentHousePriceCounts'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AgentHousePriceCounts)
h23[[k]]<-list('AgentHousePriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AgentHousePriceMean)
h24[[k]]<-list('AgentHousePriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AgentHousePriceP50)
h25[[k]]<-list('AgentHousePriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AgentHousePriceP5)
h26[[k]]<-list('AgentHousePriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AgentHousePriceP95)
h27[[k]]<-list('CommunityHousePriceCounts'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityHousePriceCounts)
h28[[k]]<-list('CommunityHousePriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityHousePriceMean)
h29[[k]]<-list('CommunityHousePriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityHousePriceP50)
h30[[k]]<-list('CommunityHousePriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityHousePriceP5)
h31[[k]]<-list('CommunityHousePriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityHousePriceP95)
h32[[k]]<-list('ActuralPlaneStallPriceCounts'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralPlaneStallPriceCounts)
h33[[k]]<-list('ActuralPlaneStallPriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralPlaneStallPriceMean)
h34[[k]]<-list('ActuralPlaneStallPriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralPlaneStallPriceP50)
h35[[k]]<-list('ActuralPlaneStallPriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralPlaneStallPriceP5)
h36[[k]]<-list('ActuralPlaneStallPriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralPlaneStallPriceP95)
h37[[k]]<-list('ActuralMechanicalStallMPriceCoun'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralMechanicalStallMPriceCoun)
h38[[k]]<-list('ActuralMechanicalStallMPriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralMechanicalStallMPriceMean)
h39[[k]]<-list('ActuralMechanicalStallMPriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralMechanicalStallMPriceP50)
h40[[k]]<-list('ActuralMechanicalStallMPriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralMechanicalStallMPriceP5)
h41[[k]]<-list('ActuralMechanicalStallMPriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ActuralMechanicalStallMPriceP95)
h42[[k]]<-list('CommunityPlaneStallPriceCounts'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityPlaneStallPriceCounts)
h43[[k]]<-list('CommunityPlaneStallPriceMean'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityPlaneStallPriceMean)
h44[[k]]<-list('CommunityPlaneStallPriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityPlaneStallPriceP50)
h45[[k]]<-list('CommunityPlaneStallPriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityPlaneStallPriceP5)
h46[[k]]<-list('CommunityPlaneStallPriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityPlaneStallPriceP95)
h47[[k]]<-list('CommunityMechanicalStallPriceCou'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityMechanicalStallPriceCou)
h48[[k]]<-list('CommunityMechanicalStallPriceMea'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityMechanicalStallPriceMea)
h49[[k]]<-list('CommunityMechanicalStallPriceP50'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityMechanicalStallPriceP50)
h50[[k]]<-list('CommunityMechanicalStallPriceP5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityMechanicalStallPriceP5)
h51[[k]]<-list('CommunityMechanicalStallPriceP95'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$CommunityMechanicalStallPriceP95)
h52[[k]]<-list('LivableIndicatorDistance1'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance1)
h53[[k]]<-list('LivableIndicatorDistance2'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance2)
h54[[k]]<-list('LivableIndicatorDistance3'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance3)
h55[[k]]<-list('LivableIndicatorDistance4'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance4)
h56[[k]]<-list('LivableIndicatorDistance5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance5)
h57[[k]]<-list('LivableIndicatorDistance6'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistance6)
h58[[k]]<-list('LivableIndicatorDistanceSpare1'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare1)
h59[[k]]<-list('LivableIndicatorDistanceSpare2'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare2)
h60[[k]]<-list('LivableIndicatorDistanceSpare3'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare3)
h61[[k]]<-list('LivableIndicatorDistanceSpare4'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare4)
h62[[k]]<-list('LivableIndicatorDistanceSpare5'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare5)
h63[[k]]<-list('LivableIndicatorDistanceSpare6'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare6)
h64[[k]]<-list('LivableIndicatorDistanceSpare7'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare7)
h65[[k]]<-list('LivableIndicatorDistanceSpare8'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare8)
h66[[k]]<-list('LivableIndicatorDistanceSpare9'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$LivableIndicatorDistanceSpare9)
h67[[k]]<-list('ContractNote'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ContractNote)
h68[[k]]<-list('ContractUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ContractUnitPrice)
h69[[k]]<-list('ContractTownhouseUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ContractTownhouseUnitPrice)
h70[[k]]<-list('ContractTownhouseLandUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ContractTownhouseLandUnitPrice)
h71[[k]]<-list('ContractTotalPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$ContractTotalPrice)
h72[[k]]<-list('AvgPlaneStallEstUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AvgPlaneStallEstUnitPrice)
h73[[k]]<-list('AvgMechanicalStallEstUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMINPUT$AvgMechanicalStallEstUnitPrice)
h74[[k]]<-list('Seg'=t(json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$H02)[3])
h75[[k]]<-list('T1ModelName'=t(json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$H02)[4])
h76[[k]]<-list('T1_OriginalScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$T1ScoreResult$OriginalScore)
h77[[k]]<-list('T1_TransformedScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$T1ScoreResult$TransformedScore)
h78[[k]]<-list('T2_OriginalScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$T2ScoreResult$OriginalScore)
h79[[k]]<-list('T2_TransformedScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$T2ScoreResult$TransformedScore)
h80[[k]]<-list('FinalScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalScore)
h81[[k]]<-list('FinalTransformedScore'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalTransformedScore)
h82[[k]]<-list('HpmUnitPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$HpmUnitPrice)
h83[[k]]<-list('HpmTotalPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$HpmTotalPrice)
h84[[k]]<-list('HpmModelFlag'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$HpmModelFlag)
h85[[k]]<-list('StallFlag'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$StallFlag)
h86[[k]]<-list('PolicyHousePrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$PolicyHousePrice)
h87[[k]]<-list('PolicyStallPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$PolicyStallPrice)
h88[[k]]<-list('PolicyTotalPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$PolicyTotalPrice)
h89[[k]]<-list('PolicyTotalPriceWithStall'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$PolicyTotalPriceWithStall)
h90[[k]]<-list('FinalHousePrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalHousePrice)
h91[[k]]<-list('FinalStallPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalStallPrice)
h92[[k]]<-list('FinalTotalPrice'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalTotalPrice)
h93[[k]]<-list('FinalTotalPriceWithStall'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$FinalTotalPriceWithStall)
h94[[k]]<-list('HierachyFlag'	=json_data[[k]]$PerformanceStatistic$PCSMOUTPUT$HierachyFlag)
 final[[k]] <- c(no[[k]],h1[[k]],h2[[k]],h3[[k]],h4[[k]],h5[[k]],h6[[k]],h7[[k]],h8[[k]],h9[[k]],h10[[k]]
 ,h11[[k]],h12[[k]],h13[[k]],h14[[k]],h15[[k]],h16[[k]],h17[[k]],h18[[k]],h19[[k]],h20[[k]]
 ,h21[[k]],h22[[k]],h23[[k]],h24[[k]],h25[[k]],h26[[k]],h27[[k]],h28[[k]],h29[[k]],h30[[k]]
 ,h31[[k]],h32[[k]],h33[[k]],h34[[k]],h35[[k]],h36[[k]],h37[[k]],h38[[k]],h39[[k]],h40[[k]]
 ,h41[[k]],h42[[k]],h43[[k]],h44[[k]],h45[[k]],h46[[k]],h47[[k]],h48[[k]],h49[[k]],h50[[k]]
 ,h51[[k]],h52[[k]],h53[[k]],h54[[k]],h55[[k]],h56[[k]],h57[[k]],h58[[k]],h59[[k]],h60[[k]]
 ,h61[[k]],h62[[k]],h63[[k]],h64[[k]],h65[[k]],h66[[k]],h67[[k]],h68[[k]],h69[[k]],h70[[k]]
 ,h71[[k]],h72[[k]],h73[[k]],h74[[k]],h75[[k]],h76[[k]],h77[[k]],h78[[k]],h79[[k]],h80[[k]]
 ,h81[[k]],h82[[k]],h83[[k]],h84[[k]],h85[[k]],h86[[k]],h87[[k]],h88[[k]],h89[[k]],h90[[k]]
 ,h91[[k]],h92[[k]],h93[[k]],h94[[k]])
 write.table(final[[k]], file = paste(gsub(".json","",listjson[k]),".txt", sep = ""),sep=",",append=F,col.names = TRUE,row.names=F,quote = TRUE)
}

